# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: used-cars-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usedcars
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: